alias ll='ls -l'
alias s='stty sane'
alias sa='source .venv/bin/activate'
alias dcu='docker-compose up'
alias dcud='docker-compose up -d'
alias dcd='docker-compose down'
alias dcdv='docker-compose down -v'
alias rlud='./scripts/run-local.sh up -d'
alias rldv='./scripts/run-local.sh down -v'
alias ad='cd /home/milosz/Arbeit/drivr'
alias adv='cd /home/milosz/Arbeit/drivr-values'
alias epp='export PYTHONPATH=$(pwd)'
alias ekc='export KUBECONFIG=$(pwd)/kubeconfig'
alias mrh='make run-hooks'
alias auh='alembic upgrade head'
alias ara='alembic revision --autogenerate'
alias csi='cockroach sql --insecure'

